source "https://rubygems.org"

gem 'json-ld', github: 'ruby-rdf/json-ld', branch: 'develop'
gem 'nokogiri'
gem 'htmlbeautifier'
gem 'linkeddata'
gem 'colorize'
gem 'rake', '~> 13.4.2'
gem 'haml'
gem 'redcarpet'