# SPDX-FileCopyrightText: 2026 Blackcat Informatics Inc. <paudley@blackcatinformatics.ca>
# SPDX-License-Identifier: MIT OR Apache-2.0 OR MulanPSL-2.0

PREFIX ex: <http://example.org/>
SELECT ?from ?to WHERE { ?from ex:link ?to }
