# SPDX-FileCopyrightText: 2026 Blackcat Informatics Inc. <paudley@blackcatinformatics.ca>
# SPDX-License-Identifier: MIT OR Apache-2.0 OR MulanPSL-2.0

PREFIX ex: <http://example.org/>
SELECT ?o WHERE { ex:s (ex:t|^ex:q|ex:p/ex:r) ?o }
