PREFIX ex: <http://example.org/>
SELECT ?remote ?copy ?tag WHERE {
  SERVICE <http://example.org/service/a> {
    ?remote ex:p ex:o ; ex:tag ?tag .
    BIND(?remote AS ?copy)
  }
  FILTER(sameTerm(?remote, ?copy))
}
