# SPDX-FileCopyrightText: 2026 Blackcat Informatics Inc. <paudley@blackcatinformatics.ca>
# SPDX-License-Identifier: MIT OR Apache-2.0 OR MulanPSL-2.0

SELECT ?a ?b WHERE {
  SERVICE <http://example.org/service/a> {
    SELECT ?a ?b WHERE { VALUES (?a ?b) { (UNDEF UNDEF) (UNDEF UNDEF) } }
  }
}
