# SPDX-FileCopyrightText: 2026 Blackcat Informatics Inc. <paudley@blackcatinformatics.ca>
# SPDX-License-Identifier: MIT OR Apache-2.0 OR MulanPSL-2.0

PREFIX ex: <http://example.org/>
SELECT ?a ?b WHERE {
  { SELECT ?a WHERE { SERVICE <http://example.org/service/a> { ?a ex:p ex:o } } }
  { SELECT ?b WHERE { SERVICE <http://example.org/service/b> { ?b ex:p ex:o } } }
  FILTER(!sameTerm(?a, ?b))
}
