PREFIX ex: <http://example.org/>
SELECT ?existing ?local ?remote WHERE {
  SERVICE <http://example.org/service/a> { BIND(BNODE() AS ?remote) }
  ?existing ex:p ex:o .
  BIND(BNODE() AS ?local)
  FILTER(!sameTerm(?existing, ?local) && !sameTerm(?existing, ?remote) && !sameTerm(?local, ?remote))
}
