name: Automatic Report and Test Manifest Generation
on:
  push:
    branches: [main]
  pull_request:
    branches: [ main ]

jobs:
  check_build:
    name: Try generating reports using Ruby
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.3
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          bundle install
          bundle exec rake
          git add --force '**/*.html'
          git diff-index --quiet HEAD || git commit -m "Regenerate website" --dry-run

  build_and_push:
    name: Generate reports using Ruby and push them to the gh-pages branch
    if: github.repository == 'w3c/rdf-tests' && github.ref_name == 'main'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'gh-pages'
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.3
      - run: |      
          git config user.name github-actions
          git config user.email github-actions@github.com
          git merge --strategy-option theirs origin/main
          git push
          bundle install
          bundle exec rake
          git add --force '**/*.html'
          git diff-index --quiet HEAD || git commit -m "Regenerate website"
          git push
